spring:
  config:
    activate:
      on-profile: development
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/dalcom
    username: dalcom_admin
    password: thisispassword123!
  jpa:
    hibernate:
      ddl-auto: create

cloud:
  aws:
    credentials:
      access-key: ${AWS_ACCESS_KEY}
      secret-key: ${AWS_SECRET_KEY}
