spring:
  config:
    activate:
      on-profile: development
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/dalcom
    username: dalcom_admin
    password: thisispassword123!
  jpa:
    hibernate:
      ddl-auto: update

cloud:
  aws:
    credentials:
      access-key: ${AWS_ACCESS_KEY}
      secret-key: ${AWS_SECRET_KEY}

    s3:
      presigned-url:
        expiration-time-min: 60
        bucket-name: ${AWS_S3_BUCKET}

  ncp:
    clova-speech:
      callback-url-template: https://fdc3-221-148-248-129.ngrok-free.app/api/v1/presentations/%d/speeches/%d/clova-result-callback

wasak:
  api:
    host: http://localhost:8000
