name: CICD

on:
  push:
    branches: [deploy]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3.5.3
      
      - name: Docker Setup Buildx
        uses: docker/setup-buildx-action@v2.8.0
      
      - name: Login to DockeHub
        uses: docker/login-action@v2.2.0
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
        
      - name: Generate Environment Variables Files For Production
        run: |
          echo "VARIABLE=$VARIABLE" >> ./.env
        env:
          VARIABLE: ${{ secrets.VARIABLE }}
      
      - name: Setup Java JDK
        uses: actions/setup-java@v1.4.4
        with:
          java-version: '17'
          distribution: 'temurin'
      
      - name: Build with Gradle
        run: ./gradlew bootJar
      
      - name: Proxy Build and Push
        uses: docker/build-push-action@v4.1.1
        with:
          context: .
          file: ./Dockerfile
          platforms: linux/amd64
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/dalcom-dev
    
  deploy:
    needs: build
    name: Deploy
    runs-on: [self-hosted, label-dalcom-dev]
    steps:
      - name: Login to ghcr
        uses: docker/login-action@v2.2.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_TOKEN }}
      
      # 돼라
      - name: Docker run
        run: |
          docker stop dalcom-dev && docker rm dalcom-dev && docker rmi ${{ secrets.DOCKERHUB_USERNAME }}/dalcom-dev:latest
          docker-compose up -d
