name: CICD

on:
  push:
    branches: [ staging, production ]

env:
  AWS_REGION: ap-northeast-2
  ECR_REGISTRY: ${{ secrets.ECR_REGISTRY }}
  ECR_REPOSITORY: dalcom


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3.5.3

      - name: Setup Java JDK
        uses: actions/setup-java@v1.4.4
        with:
          java-version: '17'

      - name: Extract branch name
        shell: bash
        run: echo "branch=${GITHUB_HEAD_REF:-${GITHUB_REF#refs/heads/}}" >> $GITHUB_OUTPUT
        id: extract_branch

      - name: Set Image Name
        id: set-image-name
        run: |
          echo "::set-output name=full_image_name::${{ env.ECR_REGISTRY }}/${{ env.ECR_REPOSITORY }}-${{ steps.extract_branch.outputs.branch }}"
          echo "::set-output name=image_name::${{ env.ECR_REPOSITORY }}-${{ steps.extract_branch.outputs.branch }}"

      - name: Set Application Setting
        id: set-application-setting
        run: |
          echo "Branch name: ${{ steps.extract_branch.outputs.branch }}"
          if [ "${{ steps.extract_branch.outputs.branch }}" == "staging" ]; then
            echo "::set-output name=application_setting::${{ secrets.APPLICATION_SETTING_STAGING }}"
          elif [ "${{ steps.extract_branch.outputs.branch }}" == "production" ]; then
            echo "::set-output name=application_setting::${{ secrets.APPLICATION_SETTING_PRODUCTION }}"
          else
            exit 1
          fi

      - name: Create application.yml
        run: |
          cd ./src/main/resources
          touch ./application-${{ steps.extract_branch.outputs.branch }}.yml
          echo "${{ steps.set-application-setting.outputs.application_setting }}" > ./application-${{ steps.extract_branch.outputs.branch }}.yml
        shell: bash

      - name: Gradle Setup
        uses: gradle/gradle-build-action@v2.5.1
        with:
          gradle-version: 8.1.1

      - name: Gradle Caching
        uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}-${{ steps.extract_branch.outputs.branch }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Build with Gradle
        run: gradle build -x test

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Build, tag, and push server-deploy image to Amazon ECR
        id: build-image
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        run: |
          DATE=$(date "+%y.%m.%d")
          docker build -t ${{ steps.set-image-name.outputs.full_image_name }}:$DATE --build-arg PROFILE=${{ steps.extract_branch.outputs.branch }} ./
          docker build -t ${{ steps.set-image-name.outputs.full_image_name }}:latest --build-arg PROFILE=${{ steps.extract_branch.outputs.branch }} ./

          docker push ${{ steps.set-image-name.outputs.full_image_name }}:$DATE
          docker push ${{ steps.set-image-name.outputs.full_image_name }}:latest

  deploy:
    needs: build
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Extract branch name
        shell: bash
        run: echo "branch=${GITHUB_HEAD_REF:-${GITHUB_REF#refs/heads/}}" >> $GITHUB_OUTPUT
        id: extract_branch

      - name: Set Image Name
        id: set-image-name
        run: |
          echo "::set-output name=full_image_name::${{ env.ECR_REGISTRY }}/${{ env.ECR_REPOSITORY }}-${{ steps.extract_branch.outputs.branch }}"
          echo "::set-output name=image_name::${{ env.ECR_REPOSITORY }}-${{ steps.extract_branch.outputs.branch }}"

      - name: Set Application Setting
        id: set-application-setting
        run: |
          if [ "${{ steps.extract_branch.outputs.branch }}" == "staging" ]; then
            echo "::set-output name=application_setting::${{ secrets.APPLICATION_SETTING }}"
            echo "length:"
            echo "${{ steps.set-application-setting.outputs.application_setting }}" | awk '{print length}'
          elif [ "${{ steps.extract_branch.outputs.branch }}" == "production" ]; then
            echo "::set-output name=application_setting::${{ secrets.APPLICATION_SETTING_PRODUCTION }}"
            echo "length:"
            echo "${{ steps.set-application-setting.outputs.application_setting }}" | awk '{print length}'
          else
            exit 1
          fi

      - name: Deploy on server
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.AWS_HOST_DEPLOY }}
          username: ${{ secrets.AWS_SSH_USERNAME }}
          key: ${{ secrets.AWS_SSH_KEY }}
          script_stop: true
          script: |
            echo "size: "
            echo "${{ steps.set-application-setting.outputs.application_setting }}" | awk '{print length}'

            password=$(aws ecr get-login-password --region ${{ env.AWS_REGION }})
            docker login --username AWS --password $password ${{ env.ECR_REGISTRY }}
            docker pull ${{ steps.set-image-name.outputs.full_image_name }}:latest
            docker container stop ${{ steps.set-image-name.outputs.image_name }} 2>/dev/null || true
            docker container rm ${{ steps.set-image-name.outputs.image_name }} 2>/dev/null || true
            docker run --net=host --restart on-failure:10 -d -p 8080:8080 --name ${{ steps.set-image-name.outputs.image_name }} ${{ steps.set-image-name.outputs.full_image_name }}:latest
            docker images | awk '$1 == "${{ steps.set-image-name.outputs.full_image_name }}" && $2 == "<none>" {print $3}' | xargs -I {} docker rmi {}
